### ISSUE TITLE
fun facts about stuff.wav

### ISSUE THREAD

**Issue by eijrin** [eip618/eiphax-facts#1]
1) 1ft of moving water will make many vehicles float away, while only 2 feet of moving water can float a large vehicle such as bus.

2) 6 inches of fast-moving flood water has enough strength to knock a person down/off their feet)

3) Wimbledon tennis balls are kept at 68⁰F/20⁰C. All 50,000+ of them!

**Comment by eijrin** [comment]
When whales and dolphins get old they have no energy to resurface and thus die from suffocation in the deep dark ocean.

**Comment by eip618** [comment]
all facts must have a source or citation

**Comment by eijrin** [comment]
1) https://weather.com/safety/floods/news/flash-flooding-vehicle-danger-20140717
2) https://plumbing-connection.com/blog/only-6-inches-of-flood-water-can-knock-you-down-flash-flood-facts-and-safety-tips/
3) https://www.wimbledondebentureholders.com/articles/2019/10/01/how-many-balls-used-wimbledon/
4) https://a-z-animals.com/blog/how-do-whales-die-7-common-causes-of-death-for-whales/ "If an elderly whale becomes sick or disabled, it may not be able to surface to breathe. Therefore, it drowns. Drowning rather than old age could therefore be named the cause of death."

dolphins are just small whales cetaceans so same thing

**Comment by eip618** [comment]
added
