### ISSUE TITLE
more fact

### ISSUE THREAD

**Issue by eijrin** [eip618/eiphax-facts#3]
1. **We are closer to the T-Rex in time than the T-Rex was to the Stegosaurus** Source: [Stegosaurus Wikipedia article states the stegosaurus had been extinct for 85-90m years before the t-rex existed](https://en.wikipedia.org/wiki/Stegosaurus) and a [Wikipedia article states the Tyrannosaurus rex lived 65m years ago](https://en.wikipedia.org/wiki/Tyrannosaurus)

2. **Harvard University was founded before calculus was discovered** Source: [Harvard was founded in 1636](https://www.harvard.edu/history) [Calculus wasn't discovered until roughly 50 years later, thanks to [Gottfried Leibniz's 1684 "Nova Methodus" and Isaac Newton's 1687 "Principia"](http://www.math.rutgers.edu/courses/436/Honors02/newton.html) + refinements in later years.

3. **A man received the highest honor of service from both the Allies and Axis in World War II** [Double Agent Joan Pujol Garcia was eventually given both the Iron Cross by the Germans and the Most Excellent Order by the British Empire. ](https://www.thedailybeast.com/the-spy-who-tricked-hitler-the-story-of-double-agent-juan-pujol-and-d-day)

4. [Heroin was once used to treat children's coughs.](https://www.businessinsider.com/yes-bayer-promoted-heroin-for-children-here-are-the-ads-that-prove-it-2011-11?op=1&r=US&IR=T)

5. [North Korea and Finland are technically separated by only one country](https://i.insider.com/53c02f4769beddd32f78d754?width=700&format=jpeg&auto=webp)

6. [There's a nuclear bomb lost somewhere off the coast of Georgia](https://www.npr.org/2008/02/03/18587608/for-50-years-nuclear-bomb-lost-in-watery-grave)

7. [A con man sold the Eiffel Tower, nearly twice!](https://www.smithsonianmag.com/history/the-smoothest-con-man-that-ever-lived-29861908/?no-ist)

8. [Tomatoes were once thought to be poisonous](https://www.thespruceeats.com/history-of-tomatoes-as-food-1807678#:~:text=A%20member%20of%20the%20deadly,likely%20yellow%20rather%20than%20red.)

**Comment by eip618** [comment]
👍
