### ISSUE TITLE
haha more fact (when do eijr colour)

### ISSUE THREAD

**Issue by eijrin** [eip618/eiphax-facts#4]
1.  [The Guinness Book of World Records... holds the world record for being the book most often stolen from public libraries.](https://did-you-know.net/fun/guiness-book-world-records-holds-record-being-book-most-stolen-public-libraries/)
 

2. [In the 1830s, tomato ketchup was sold as a medicine, claiming to cure ailments like diarrhea, indigestion, and jaundice](https://historyofyesterday.com/ketchup-was-sold-as-medicine-in-the-1800s-8b601329bc28)

3. [Sound waves travel over 17 times faster through steel than through air.](https://www.schoolnet.org.za/PILAfrica/en/webs/19537/physics4.html#:~:text=This%20is%20because%20molecules%20in,per%20second%20(13%2C332%20mph)!)

4. The bone that supports your eyeball, called the orbital floor, is paper thin and has a large empty cavity, called the maxillary sinus, on the opposite side. When you get hit hard in the eyeball, instead of your eyeball itself rupturing, the bone underneath your eye breaks, which is called an orbital floor fracture. This releases the pressure from the impact and saves your eyeball. (eip is doctor do i need source or well your wife is)

5. [There's a small fishing village/tribe in Asia where the fisherman have evolved to be able to hold their breath for around 10 minutes while hunting underwater.](https://historyofyesterday.com/the-people-from-bajau-tribe-can-hold-their-breath-underwater-for-13-minutes-a7a8d22d1b06#:~:text=The%20Bajau%20tribe&text=For%20many%20years%20this%20tribe,60%25%20of%20the%20time%20underwater.)

6. [The smell of rain or disturbed small is a compound produced by bacteria called Geosmin, and the human nose is extremely sensitive to it. We can smell it at as low a concentration as 5 parts per trillion.](https://en.wikipedia.org/wiki/Geosmin)

BONUS - [We can smell rain better than sharks can smell blood. I actually just learned about this.](https://primalderma.com/the-scent-after-the-storm/#:~:text=The%20scent%20of%20rain%2C%20petrichor,sharks%20are%20at%20smelling%20blood.)

7. [Your liver can regenerate, and much faster than you think.](https://www.mayo.edu/research/centers-programs/center-regenerative-medicine/focus-areas/liver-regeneration)

8. [Natural redheads require increased doses of anesthesia, due to some connection with the mutated melanocortin-1 receptor.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1362956/)

9. [Your immune system doesn't know your eyes exist. There's a chance that if you get an eye injury or an infection near your eyes the immune system will think your eyes are a foreign body and you'll go blind](https://www.aao.org/eye-health/tips-prevention/eye-immune-privilege)

10. [Babies are born without bone kneecaps, they develop around 2 years after birth](url)

11. [When we get sunburn, that's not the heat of the sun that's hurting us most of the time, but it's little skin cells killing themselves to protect us from skin cancer.](https://www.independent.co.uk/news/body-tells-sunburnt-cells-commit-suicide-1110912.html)

12. [Some people can control tensor tympani to change sounds in their ears](https://ctsciencecenter.org/blog/useless-super-powers/#:~:text=Well%2C%20apparently%20there%20are%20some,auditory%20tube%20in%20their%20ear.)

**Comment by eip618** [comment]
👍
